___

<a href='http://pvs.bilecik.edu.tr/salim.ceyhan/'> <img src='../images/numpyexer.png' /></a>
___


# NumPy Alıştırmaları

NumPy'yi öğrendiğimize göre şimdi bilginizi test edelim. Birkaç basit görevle başlayacağız ve ardından daha karmaşık sorular sorulacak.

<div class="alert alert-danger" style="margin: 10px"><strong>ÖNEMLİ NOT!</strong> Hücreleri, gösterilen örnek çıktının hemen üzerinde çalıştırmadığınızdan emin olun, aksi takdirde örnek çıktının üzerine yazacaksınız!</div>

1. Import NumPy as np

In [1]:
import numpy as np

2. Tüm elemanları 0  olan 10 elemanlı bir dizi oluşturun.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Tüm elemanları 1 olan 10 elemanlı bir dizi oluşturun.

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Tüm elemanları 5 olan 10 elamanlı dizi oluşturun.

In [4]:
np.ones(10) * 5 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. 10'dan 50'ye kadar bir tamsayı dizisi oluşturun.

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. 10'dan 50'ye kadar ki tüm çift tam sayıların bir dizisini oluşturun.

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. 0 ile 8 arasında değişen tam sayı değerlere sahip 3x3'lük bir matris oluşturun.

In [7]:
np.array([[0,1,2], [3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. 3x3'lük bir birim matris oluşturun.

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# DON'T WRITE HERE

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. 0 ile 1 arasında rastgele bir sayı oluşturmak için NumPy kullanın.
<br><br>&emsp;NOT: Sonucunuzun değeri aşağıda gösterilenden farklı olabilir.

In [9]:
np.random.rand(1)

array([0.70920572])

In [9]:
# DON'T WRITE HERE

array([0.65248055])

10. Standart bir normal dağılımdan örneklenmiş 25 rastgele sayıdan oluşan bir $5\times5$'lik bir matris oluşturmak için NumPy kullanın<br><br>&emsp;&ensp;NOT:  Sonucunuzun değeri aşağıda gösterilenden farklı olabilir.

In [16]:
np.random.randn(5,5)

array([[-0.95297079, -0.88673325,  0.69122656, -0.3285603 ,  1.12122494],
       [ 0.00688964, -0.83699029,  2.17242465, -1.53708207,  1.0261611 ],
       [ 1.04685738, -1.82559289,  0.30393609,  1.11500866,  1.02618903],
       [ 1.15200113, -0.04971898,  0.54428416, -0.17689394,  0.36736233],
       [ 0.7557099 , -0.16099238, -1.04250873, -0.11548135, -0.10052835]])

In [10]:
# DON'T WRITE HERE

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

11. Aşağıdaki matrisi oluşturun.

In [26]:
np.linspace(0.01, 1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [11]:
# DON'T WRITE HERE

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. 0 ile 1 arasında doğrusal olarak eşit aralıklı 20 noktadan oluşan bir dizi oluşturun.

In [27]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# DON'T WRITE HERE

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy İle İndeksleme ve Seçme
Bu bölümde, bir başlangıç matrisi üzerinde indeksleme ve seçme işlemlerini nasıl gerçekleştireceğinizi öğreneceksiniz. Örnek matrisi kullanarak belirli matris çıktılarını elde edebilmek için indeksleme ve seçme yöntemlerini kullanmanız gerekecek. Bu, NumPy dizileri üzerindeki yeteneğinizi test etmek için harika bir alıştırma olacaktır.

In [28]:
# BU HÜCREYİ ÇALIŞTIR - BU BAŞLANGIÇ MATRİSİNİZ OLACAK
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

13. Aşağıda gösterilen çıktıyı yeniden üreten bir kod yazın.

In [86]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# DON'T WRITE HERE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

14. Aşağıda gösterilen çıktıyı yeniden üreten bir kod yazın.

In [33]:
mat[3,4]

20

In [15]:
# DON'T WRITE HERE

20

15. Aşağıda gösterilen çıktıyı yeniden üreten bir kod yazın.

In [59]:
mat[:3, 1:2:1]

array([[ 2],
       [ 7],
       [12]])

In [16]:
# DON'T WRITE HERE

array([[ 2],
       [ 7],
       [12]])

16. Aşağıda gösterilen çıktıyı yeniden üreten bir kod yazın.

In [64]:
mat[4:,]

array([[21, 22, 23, 24, 25]])

In [17]:
# DON'T WRITE HERE

array([21, 22, 23, 24, 25])

17. Aşağıda gösterilen çıktıyı yeniden üreten bir kod yazın.

In [65]:
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# DON'T WRITE HERE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy İşlemleri

18. mat 'daki tüm değerlerin toplamını alın.

In [67]:
mat.sum()

325

In [19]:
# DON'T WRITE HERE

325

19. mat matrisindeki tüm değerlerin standart sapmasını alın

In [68]:
mat.std()

7.211102550927978

In [20]:
# DON'T WRITE HERE

7.211102550927978

20. mat'daki tüm sütunların toplamını alın

In [69]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [21]:
# DON'T WRITE HERE

array([55, 60, 65, 70, 75])

## Bonus Soru

### Bilgi

Numpy ile rastgele sayılar üretirken, aynı rastgele sayı dizisini tekrar tekrar elde etmek için `numpy.random.seed()` fonksiyonunu kullanabilirsiniz. Bu fonksiyon, rastgele sayı üreticisinin başlangıç noktasını (tohum değerini) ayarlamanıza izin verir. Böylece, aynı tohum değeriyle çalıştığınızda her seferinde aynı rastgele sayı dizisini elde edersiniz. Bu özellik, rastgele sayıların tutarlı olmasını sağlamak için, özellikle deneylerin veya analizlerin tekrarlanabilir olması gerektiğinde oldukça kullanışlıdır.

Bunun için yapılması gereken kodlamayı aşağıya yazınız:

In [84]:
np.random.seed(1)
deneme=np.random.rand()
print(deneme)

np.random.seed(1)
deneme1=np.random.rand()
print(deneme1)

0.417022004702574
0.417022004702574
